In [ ]:
#spam mail mails

#non spam mei
#offical email- correct domain
#source identification
#word frequency


#keyword matching

#spam
#keyword matching
#contextual info
#improper formatting

In [ ]:
#notebook
#script

In [ ]:
#rule based model
#ML models
#LLM based models

In [ ]:
microsoft
rnicrosoft

In [1]:
marks = [45, 60, 72, 38, 90]

total = 0

for i in range(len(marks) - 1):
    total += marks[i]

average = total / len(marks)

if average >= 50:
    print("Class passed")
else:
    print("Class failed")

print("Average:", average)

Class failed
Average: 43.0

In [ ]:
#notebook first, engineering next

#first_experiment_notebook.ipynb
#data_cleaning
#training
#evaluating
#app

In [4]:
import pandas as pd

In [5]:
data = {
    "student_id": [101, 102, 103, 104, 105, 106],
    "attendance_percent": [92, 67, 81, 45, 74, 88],
    "assignment_score": [18, 12, 15, 8, 14, 19],
    "quiz_score": [72, 48, 65, 30, 55, 80],
    "lab_completed": [True, False, True, False, True, True]
}
df = pd.DataFrame(data)
df

   student_id  attendance_percent  assignment_score  quiz_score  lab_completed
0         101                  92                18          72           True
1         102                  67                12          48          False
2         103                  81                15          65           True
3         104                  45                 8          30          False
4         105                  74                14          55           True
5         106                  88                19          80           True

In [6]:
df.shape

(6, 5)

In [8]:
df.head()

   student_id  attendance_percent  assignment_score  quiz_score  lab_completed
0         101                  92                18          72           True
1         102                  67                12          48          False
2         103                  81                15          65           True
3         104                  45                 8          30          False
4         105                  74                14          55           True

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   student_id          6 non-null      int64
 1   attendance_percent  6 non-null      int64
 2   assignment_score    6 non-null      int64
 3   quiz_score          6 non-null      int64
 4   lab_completed       6 non-null      bool
dtypes: bool(1), int64(4)
memory usage: 330.0 bytes

In [11]:
df.describe ()

       student_id  attendance_percent  assignment_score  quiz_score
count    6.000000            6.000000          6.000000    6.000000
mean   103.500000           74.500000         14.333333   58.333333
std      1.870829           17.073371          4.033196   18.007406
min    101.000000           45.000000          8.000000   30.000000
25%    102.250000           68.750000         12.500000   49.750000
50%    103.500000           77.500000         14.500000   60.000000
75%    104.750000           86.250000         17.250000   70.250000
max    106.000000           92.000000         19.000000   80.000000

In [12]:
df["total_scores"]= df["assignment_score"]+ df["quiz_score"]
df

,student_id,attendance_percent,assignment_score,quiz_score,lab_completed,total_scores
0,101,92,18,72,True,90
1,102,67,12,48,False,60
2,103,81,15,65,True,80
3,104,45,8,30,False,38
4,105,74,14,55,True,69
5,106,88,19,80,True,99

In [13]:
df["eligible"]=(
    (df["attendance_percent"]>=75) &
    (df["total_scores"]>=50) &
    (df["lab_completed"]==True)

)
df

,student_id,attendance_percent,assignment_score,quiz_score,lab_completed,total_scores,eligible
0,101,92,18,72,True,90,True
1,102,67,12,48,False,60,False
2,103,81,15,65,True,80,True
3,104,45,8,30,False,38,False
4,105,74,14,55,True,69,False
5,106,88,19,80,True,99,True

In [15]:
eligible_students = df[df["eligible"] == True]
eligible_students

,student_id,attendance_percent,assignment_score,quiz_score,lab_completed,total_scores,eligible
0,101,92,18,72,True,90,True
2,103,81,15,65,True,80,True
5,106,88,19,80,True,99,True